# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('translations', models.ManyToManyField(related_name='_word_translations_+', to='words.Word')),
            ],
        ),
    ]
