# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='_word_antonyms_+', to='words.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_word_translations_+', to='words.Word'),
        ),
    ]
