# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20160515_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('kz', 'kazakh'), ('ru', 'russian')], max_length=2),
        ),
    ]
